#+title: Traduction professionnelle et collaborative

Interview de *Samy Boutayeb*

L'interview est lisible dans sa version finalisée sur [[http://www.withoutmodel.com/fr/samy-boutayeb/dans-la-traduction-la-collaboration-est-devenue-la-regle/][withoutmodel.com]]

L'auteur est traducteur professionnel. Il a été pendant plus de 10 ans
enseignant-chercheur en sciences du langage et en français langue
étrangère, dans différentes universités en France et en Allemagne. Il
a traduit par la suite une vingtaine d'ouvrages, essentiellement dans
le domaine informatique, pour le compte de maisons d'édition
françaises. Exerçant en statut indépendant depuis plus de 15 ans, il
pratique à titre professionnel l'activité de traducteur-réviseur. Une
activité passionnante qu'il prolonge, dans un cadre collaboratif, pour
le projet Global Voices, "une communauté sans frontières,
essentiellement bénévole, de plus de 800 auteurs, analystes,
spécialistes des médias en ligne et traducteurs". Convaincu de
l'utilité sociale du partage des savoirs - une conviction renforcée
par sa rencontre avec le mouvement du logiciel libre - il a participé
à différents projets éducatifs et de développement logiciel, notamment
dans le cadre du programme "One Laptop Per Child". Il peut être
contacté à samy@langues-etcetera.fr.

Nous avons voulu comprendre l'impact du numérique sur le travail
quotidien des traducteurs professionnels - le « numérique » désignant
ici un ensemble de contenus, d'outils et de pratiques potentiellement
collaboratives.

* Comment Internet et les outils informatiques changent votre travail ?

Internet et les outils informatiques sont à l'origine d'une évolution permanente, mais qui ne touche pas directement les fondamentaux du métier. Un métier que j'ai appris et pratiqué à l'ancienne, donc sur papier, à grands coups de dictionnaires, de fréquentation de bibliothèques et de centres de documentation, puis sur machine à écrire à ruban.  C'était
l'époque héroïque des [[http://j.poitou.free.fr/pro/img-p/tkn/tw-effacer.html][gommes et caches]], indispensables pour corriger les erreurs sur l'original et le double, un exercice que l'usage du papier carbone rendait encore plus délicat.

Aujourd'hui, après un épisode « traitement de texte », la profession est définitivement en ligne - et globalisée, cela va de soi.

Tout a changé : la relation client-fournisseur, désormais adossée à des outils de gestion de la relation client ; la gestion de projet avec l'attribution des projets, l'exécution de la prestation, la remise des livrables, la facturation ; la gestion des documents : soit en édition monoposte à l'aide d'outils de TAO (« Traduction Assistée par Ordinateur »), qui utilisent une mémoire de traduction sur serveur et une base de données terminologique en ligne, soit en édition collaborative.

Nous travaillons aujourd'hui en mobilité, en réseau globalisé et à flux tendu, avec des délais de transmission qui se sont raccourcis à toutes les étapes des projets depuis l'époque, pas si lointaine, du coursier ou du courrier postal.

La recherche documentaire et terminologique multilingue, quant à elle, a bénéficié d'Internet dès les débuts, en s'appuyant sur toutes les ressources en ligne possibles et imaginables : corpus textuels multilingues, bases de données terminologiques en ligne, documents de référence pour tous les besoins du professionnel.  Exemples : dans un cadre institutionnel, la base terminologique de la Communauté Européenne [[https://fr.wikipedia.org/wiki/Terminologie_interactive_pour_l%2527Europe][IATE]] ou, dans un cadre entrepreneurial, le plus récent [[https://fr.wikipedia.org/wiki/Linguee][Linguee]], un corpus textuel couvrant plusieurs paires de langues.

L'état de l'art de la traduction collaborative emprunte aux serveurs de traductions, qui sont gérés par des systèmes de bases de données et présentent sur un navigateur Web les documents à traduire sous forme de textes segmentés dans des tableaux, les contenus étant versés dans les mémoires de traduction en réseau.  Citons, dans cette catégorie, les plateformes libres [[https://en.wikipedia.org/wiki/Pootle][Pootle]] et [[https://en.wikipedia.org/wiki/Translatewiki.net][translatewiki.net]] ou le service commercial [[https://en.wikipedia.org/wiki/Transifex][Transiflex]].

Dans la catégorie des outils à éviter, le traducteur « pro » inclura sagement [[https://fr.wikipedia.org/wiki/Google_Traduction][Google Translate]], qui n'est pas un outil au sens strict, et n'a donc pas à figurer dans la panoplie du traducteur professionnel, mais un moteur de traduction automatique, qui peut éventuellement dépanner l'amateur.  Le plus souvent, lorsque le traducteur « humain » utilise la traduction automatique, c'est pour faire de la post-édition de traductions machine, une tâche jugée ingrate et peu valorisante.

Autre changement récent, portant cette fois sur les thématiques : la traduction de mots-clés de moteurs de recherche, dans une optique SEO, ou [[https://fr.wikipedia.org/wiki/Optimisation_pour_les_moteurs_de_recherche][Search Engine Optimization]].  Enfin, parmi les outils qui apportent un plus au quotidien, on mentionnera les correcteurs orthographiques et grammaticaux, les outils d'assurance qualité, généralement intégrés aux logiciels métier, ou, dans la catégorie des technologies d'assistance, la dictée vocale.

* Quelle est la place de la collaboration dans la pratique professionnelle ?

C'est devenu la règle depuis quelques années.  Sous la houlette du chef de projet, plusieurs personnes travaillent ensemble sur les chapitres d'un manuel volumineux ou bien sur le même document découpé en segments.  Après validation par un traducteur, les traductions sont téléversées en temps réel dans une « mémoire de traduction » partagée, une sorte de base de données textuelle bilingue ou plurilingue, qui est alors mise en commun.  Dans ce mode opératoire, chaque relecteur ou traducteur peut avoir l'impression d'être seul derrière son écran, mais l'assemblage des parties des documents est traité par le chef de projet. L'enjeu est de répondre aux exigences, notamment de cohérence et de mise à jour, posées par les versions successives d'un même contenu, passé entre les mains d'une succession de contributeurs, publié dans plusieurs langues, sur plusieurs supports et intégrant différents médias.

La tendance actuelle est de mettre à disposition des acteurs du métier des outils intégrés pour la gestion de projets, la communication entre les collaborateurs ou bien l'échange des données et des documents.  Le marché des outils professionnels est dominé par une poignée d'éditeurs commerciaux qui ont intégré des fonctionnalités collaboratives à leurs logiciels mais qui s'efforcent de verrouiller leur mode de fonctionnement afin de garder leurs utilisateurs captifs.

D'autre part, l'accès aux outils d'aide à la traduction constitue un investissement à la fois technique et financier pour les traducteurs professionnels et un obstacle de même nature pour les traducteurs occasionnels.  Ces derniers peuvent contourner l'obstacle en utilisant des outils libres et de qualité professionnelle comme [[https://fr.wikipedia.org/wiki/OmegaT][OmegaT]].

* Quelles expériences de collaboration entre professionnels et amateurs ?

Généralement, ces deux univers s'ignorent.  Toutefois, sous la pression de la concurrence et dans un objectif de rationalisation, certains traducteurs professionnels tentent ce s'inspirer des bonnes pratiques du génie logiciel, en particulier pour ce qui est de la « localisation logicielle » : utilisation d'outils collaboratifs, notamment de « forges logicielles », suivi de versions d'un document, virtualisation tous azimuts, recours aux standards documentaires et
aux formats normalisés pour l'échanges de données textuelles et terminologiques - voir le TMX, [[http://www.xmlfacile.com/guide_xml/fichier_de_traduction_tmx_1.php5][Translation Memory Exchange]] pour les mémoires de traduction ou le TBX, [[http://www.tbxconvert.gevterm.net][Termbase eXchange]] pour les données terminologiques.  Dans une démarche analogue, le professionnel a tout intérêt à prendre en compte les trouvailles et solutions que les "amateurs" peuvent avoir mises au point pour leurs propres projets. Un exemple : l'édition multilingue de sous-titres, pour laquelle des logiciels de sous-titrage sous licence libre peuvent rendre de grands services aux professionnels.

Au chapitre de la collaboration entre professionnels et amateurs, [[https://globalvoices.org][Global Voices]] mérite une mention particulière.  Cette communauté s'appuie sur une excellente plateforme de traduction collaborative de
type wiki, à la fois accessible aux non professionnels et attrayante et fonctionnelle pour les professionnels.  Dans ce genre de projets communautaires, ce qui est valorisé, c'est la compétence autour d'une tâche donnée (rédaction journalistique, traduction ou autre) et la contribution concrète de chacun, quel que soit le métier ou le statut des contributeurs.

On observe également des rapprochements ponctuels, autour d'un projet, entre les acteurs professionnels du secteur des langues, apportant leur expertise et leurs ressources, et les acteurs représentant la « société civile », exprimant des besoins, notamment pour la traduction de contenus, comme on a pu le voir à Berlin, début 2016, dans le contexte de l'accueil des demandeurs d'asile arrivant en Allemagne.

* Est-ce que les contenus libres représentent un marché potentiel ?

Pour l'édition de logiciels sous licences libres, il a fallu attendre Android pour que des éditeurs d'applications s'adressent à des traducteurs professionnels pour traduire leurs interfaces ou leurs données.  Cette démarche d'éditeurs privés suppose un marché et une distribution payante des logiciels/applications ainsi localisés.

Quant aux logiciels libres, ils sont à ma connaissance exclusivement localisés de façon communautaire.  À mes yeux, les amateurs n'ont pas à rougir de s'être pris eux-mêmes en charge : le résultat est probant et la qualité est au rendez-vous.  Je ne parle même pas des volumes, qui sont extrêmement impressionnants et témoignent d'une dynamique irremplaçable.  Pour s'en convaincre, prenons par exemple la [[http://translate.sugarlabs.org/][liste des langues]] prises en compte dans le projet de la plateforme éducative [[https://www.sugarlabs.org][Sugar]] : ici, on sent que ce n'est pas le poids du marché qui a guidé la démarche, mais bien le besoin réel des locuteurs de ces langues, parfois négligées par les éditeurs commerciaux.

Dans le secteur de l'édition, les projets de traduction autour des contenus libres sont une variante intéressante à plus d'un titre : on trouve ainsi des contenus sous licence libre, traduits par des experts d'une thématique ou d'un domaine et diffusés par des éditeurs en empruntant les circuits traditionnels de l'édition, voire un double circuit libre/commercial.  Citons [[http://framabook.org/richard-stallman-et-la-revolution-du-logiciel-libre-2/][la biographie de Richard Stallman]],
parue chez Eyrolles & Framabook.  Il m'est arrivé également, en tant que professionnel, de participer à des projets dérivés de contenus libres, en réalisant des traductions éditoriales de manuels utilisateurs portant sur des logiciels libres, publiées de manière très classique, chez différents éditeurs.

Les contenus libres ont donc toute leur place dans la galaxie de la traduction et de la localisation.  Les nombreux projets de traduction collaborative qui voient le jour en sont la preuve : qu'il s'agisse de jeux, comme [[http://wiki.wesnoth.org/FrenchTranslation][Wesnoth]], de systèmes d'exploitation, comme [[https://www.debian.org/doc/manuals/intro-i18n/][Debian]] ou de logiciels éducatifs, comme [[http://educoo.org/TelechargerOOo4Kids.php][OOo4Kids]]. C'est, j'en suis convaincu, une «
nouvelle frontière », dont l'exploration ouvre des perspectives passionnantes : prenez par exemple le [[http://www.refugeephrasebook.de][Refugee Phrasebook]], un projet d'aide à la traduction pour les réfugiés, né de l'urgence et palliant
sur le terrain aux insuffisances institutionnelles, ou le projet éditorial [[http://openmodels.fr][Open Models]], s'emparant de thématiques encore trop jeunes ou insuffisamment rentables pour être récupérées par les circuits marchands.

* Quels enjeux pour cette activité de traduction, si riche et multiforme ? 

La situation que nous avons décrite est le corollaire de la
globalisation : un phénomène éminemment positif, en l'occurrence, et
dans lequel s'inscrivent les projets communautaires portés par la
société civile. Paradoxalement et malgré la multiplication des
échanges qu'implique cette globalisation, on observe que les acteurs
de cette société civile restent largement attachés à communiquer dans
leur propre langue, qui marque leur ancrage au sein de leurs
communautés locales respectives. Cet attachement à une communauté
linguistique spécifique limite, de fait, les interactions plus larges
au sein de communautés globales. Il met l'accent sur l'émergence de
besoins de communication élargis, qui constituent à leur tour un enjeu
majeur pour les acteurs de la traduction, qu'il soient professionnels
ou amateurs.
