#+TITLE: La traduction sur les Wikipédias

* Présentation

Ces témoignages croisés ont été menés par écrit : les questions ont
été postées en ligne par Bastien et les wikipédiens y ont répondu par
écrit en contribuant sur un [[https://framapad.org][framapad]].  Le contenu du pad a ensuite été
réédité pour en faciliter la lecture sans en trahir, si possible, le
contenu.

Voici la liste des wikipédiens qui ont eu la gentillesse de répondre :

- [[https://fr.wikipedia.org/wiki/Utilisateur:Trizek][Benoît Evellin]] (en tant bénévole et non en tant que salarié de la
  Wikimedia Foundation)
- [[https://fr.wikipedia.org/wiki/Utilisateur:Daehan][C. Hernandez]] 
- [[https://fr.wikipedia.org/wiki/Utilisateur:Matou91][Charlotte Matou]] 
- [[https://fr.wikipedia.org/wiki/Utilisateur:Cbyd][Dominique]]
- [[https://fr.wikipedia.org/wiki/Utilisateur:Pradoliv][Eduardo]]
- [[https://fr.wikipedia.org/wiki/Utilisateur:Otourly][Florian F.]]
- [[https://fr.wikipedia.org/wiki/Utilisateur:Pom445][Justine]]
- [[https://fr.wikipedia.org/wiki/Utilisateur:psychoslave][Mathieu Stumpf Guntz]]
- [[https://fr.wikipedia.org/wiki/Utilisateur:Rehtse][Pascal Maillard]]

Merci à eux !

* Quelle est votre expérience générale de la traduction sur Wikipédia ?

# Quelles langues, dans quel(s) but(s), à quelle fréquence, etc. ?

FF : Je traduis un peu depuis les langues romanes, l'italien et le
piémontais, dans le but d'ajouter des articles sur des événements
intéressants non traités sur Wikipédia.  Je traduis par découverte
fortuite via les articles sans interwikis des wikipédia sources ou
via des messages en PDD.

   NDE : Un lien « interwiki » est un lien interne vers un autre
   projet de la fondation Wikimedia.  Une « PDD » est une « page de
   discussion », accessible via l'onglet « Discussion » en haut à
   gauche des articles : c'est là que les contributeurs des projets
   débattent de questions sur l'édition des articles.

CM : J'ai rarement traduit (ça me rappelle trop le boulot), mais je
révise parfois des traductions, notamment depuis l'anglais, et plus
rarement depuis l'italien et le russe.  Les articles que je traduis
entrent dans une thématique sur laquelle je travaille.

CH : La majorité des articles que j'ai créés (plus de 400) sont
traduits depuis les wikipédias anglaise ou espagnole.  J'ai
ponctuellement traduit depuis l'italien et le néerlandais.

ED : Je collabore dans le domaine de la psychanalyse, la littérature,
l'histoire littéraire, le théâtre.  En général, je m'inspire des
articles d'autres wikipédias mais je ne traduis pas vraiment, les
procédures en vue d'une traduction me semblent assez compliquées.
Quand je travaille sur un article en français, je vérifie ce que les
collègues de langue anglaise en ont fait.

DC : Je m'intéresse principalement à des biographies de scientifiques
et à des distinctions.  Je remarque que souvent les wikipédias
anglophone et germanophone sont plus complètes.  Quand c'est possible,
j'utilise le wiktionnaire, en le complétant de temps en temps.  Quand
je vois un lien rouge pour lequel je me sens capable d'apporter
qqchose, je vérifie si le sujet existe dans d'autres WP, via Wikidata
notamment. Et un peu aussi des liens qui me font plaisir, sur des
auteurs ou des oeuvres que j'ai appréciés.

BE : Je traduis en fonction des sujets que j'aime bien.  Si l'article
n'existe pas sur la Wikipédia francophone mais qu'il est présent sur
l'anglophone ou l'espagnole, hop, je le traduis.

PM : Je traduis peu.  Je le fais principalement pour tester les outils
de traduction.  Je fais beaucoup de maintenance et je trouve important
de comprendre comment on peut commettre des erreurs en utilisant les
outils existants.  Je pars en général de la wikipédia anglophone, ou
bien des suggestions du bistro, ou d'un lien rouge s'il me parle.

#+BEGIN_QUOTE
NDE: Le « [[https://fr.wikipedia.org/wiki/Wikip%25C3%25A9dia:Le_Bistro][bistro]] » est un lieu d'échange ouvert entre contributeurs.
Les « liens rouges » sont des liens vers des articles qui n'existent
pas encore.
#+END_QUOTE

MSG : Je traduis des articles de temps en temps depuis l’anglais vers
le français et l’espéranto.  Pour les traductions vers l’espéranto,
les propositions d’[[https://www.apertium.org][Apertium]] sont souvent justes, et permettent de
gagner du temps, même si ça n’est pas parfait.  Si ça l'était il n’y
aurait même plus besoin de contribution humaine !  À noter qu’il
existe des traductions entièrement automatisés.

J : Je traduis la plupart du temps depuis l'anglais.  Il m'est arrivé
de travailler à partir du russe, mais cela reste rare.  Mes sujets
sont vastes : histoire, cuisine...  Je fais à l'envie, selon les sujet
qui m’intéressent, ou que j'estime incomplets sur Wikipédia.

* Quels outils utilisez-vous pour traduire ?

FF : J'utilise des dictionnaires, m'appuyant pour le piémontais sur la
ressemblance avec l'italien et le français.  Si possible je confronte
également les sources avec des versions francophones.

CH : Pour l'anglais et l'espagnol, je traduis directement ou j'utilise
le dictionnaire en ligne [[http://www.wordreference.com/fr/][Wordreference]] pour les mots plus délicats. Je
crée l'article sur wp:fr [NDE: la wikipédia francophone] et je traduis
directement à la création, je ne fais pas de brouillon en dehors ou
même dans Wikipédia.

ED: Je suis trilingue français - portugais (Brésil) - anglais.  À part
cela, je peux lire et comprendre l'espagnol et l'italien.  Je consulte
rarement [[http://translate.google.com][Google traduction]] pour voir ce qu'ils proposent.  Je consulte
aussi l'[[http://www.oed.com][Oxford English Dictionary]], mais rarement.

DC : Depuis que j'ai découvert l'outil d'assistance de traduction
([[https://fr.wikipedia.org/wiki/Sp%25C3%25A9cial:ContentTranslation][Special:ContentTranslation]]), je l'utilise plus fréquemment, surtout
depuis l'anglais et un peu depuis l'allemand, rarement depuis d'autres
langues.  Si j'ai une lacune sur un mot ou une tournure, j'utilise le
wiktionnaire ou des dictionnaires en ligne.  Souvent je traduis le RI
[Nde: Résumé introductif] et une partie du contenu, j'édite une
version inachevée et je complète ma traduction. Je laisse parfois un
paragraphe non traduit, en le signalant avec le modèle idoine, ou je
signale mes doutes en faisant confiance à l'intelligence collective
pour les pallier.

BE : Je traduis avec l'outil de traduction et, en complément,
j'utilise les outils d'assistance et [[http://www.linguee.fr/][Linguee]] pour les expressions
idiomatiques.  Special:ContentTranslation présente une assistance à la
traduction via Apertum et [[https://translate.yandex.com][Yandex]], la permanence des liens d'un article
à l'autre, la transcription des modèles et plus encore !  À noter
l'outil ne permet pas de faire de traduction collaborative.

DC : Comme BE, Special:ContentTranslation est un outil certes
imparfait mais vraiment pratique pour certaines parties (catégories,
liens, modèles...) et qui s'améliore d'année en année.

PM : Avec l'outil de traduction.

J : J'utilise le wiktionnaire, yandex et un dictionnaire papier.

* Est-ce que la Wikimedia Foundation (ou Wikimédia France) a une politique particulière vis-à-vis des questions de traduction ?

CM : La [[https://wikimediafoundation.org][Wikimedia Fondation]] s'intéresse de très près à la traduction
et cherche à améliorer les outils.  [[http://www.wikimedia.fr][Wikimédia France]] ne s'est pas
vraiment saisi de la question, bien qu'elle promeuve les wikis en
langues de France.  L'association a été contactée par une plateforme
de traduction appartenant à une agence pour que ses membres traduisent
des extraits de l'encyclopédie sur sa plateforme, afin qu'ils puissent
faire la démonstration de leurs compétences en traduction.

DC : le déploiement de [[https://www.wikidata.org/wiki/Wikidata:Main_Page][Wikidata]] facilite les connexions entre les
wikis et les traductions. Je suppose donc que c'est une volonté
délibérée, sans savoir si c'est vraiment une « politique ».

* Comment sait-on si un article de la Wikipédia francophone a été traduit depuis un article d'une Wikipédia d'une autre langue ?

FF : Pour la traduction entre les différents articles, on utilise le
modèle ={{Traduction/Référence}}= qui indique la version d'origine et y
ajoute un lien, il y a aussi le modèle ={{Traduit de}}= qui est à placer
en PDD (je n'utilise que la première solution).  Sur [[https://fr.wikinews.org/wiki/Accueil][Wikinews]], où il
m'est également arrivé de traduire des articles, on préfère importer
les articles à traduire, comme ça le bon auteur est réellement crédité
et on peut le retrouver dans l'historique.

#+BEGIN_QUOTE
NDE : Les « modèles » (ou /templates/ en anglais), sont des éléments
qu'on peut ajouter au contenu brut d'une page wikipédia, et dont la
syntaxe permet de générer un affichage particulier.  Par exemple
={{refnec}}= est un modèle souvent utilisé pour indiquer qu'une
référence est nécessaire ([[https://fr.wikipedia.org/wiki/Mod%25C3%25A8le:R%25C3%25A9f%25C3%25A9rence_n%25C3%25A9cessaire][plus de détails sur refnec]]).
#+END_QUOTE

PM : Jusqu'il y a peu, on le savait grâce au modèle
={{Traduction/Référence}}=, mais on m'a signalé que ce n'est plus
obligatoire.  C'était compliqué pour l'outil de traduction d'apposer
automatiquement le modèle, alors les légistes de la fondation ont fini
par trouver qu'il suffit d'ajouter un simple lien dans le commentaire
des modifications de l'article traduit vers l'article source.  Lorsque
j'ai constaté que les nouvelles traductions oubliaient souvent le
crédit d'auteurs, j'ai voulu modifier la page d'aide sur le sujet pour
signaler que c'est obligatoire, mais j'ai été réverté [NDE: un autre
contributeur a annulé la contribution] : ce n'est donc pas
obligatoire.  Il faut consulter la première ligne de l'historique d'un
article pour le savoir.  Auparavant, c'était souvent omis, et il n'y
avait même pas la première ligne de l'historique pour le savoir.

* Est-ce que vous vous organisez en ligne avec d'autres pour travailler sur des traductions avant de les poster sur Wikipédia ?

FF : Non, les sujets qui m'intéressent sont trop spécifiques, mais
j'en discute une fois traduit pour que d'autres les
complètent/corrigent s'ils le souhaitent.

CH : J'ai - rarement : deux fois, de mémoire - créé une simple ébauche
puis sollicité de l'aide sur un projet lié ou à un utilisateur en
particulier, pour profiter des spécialisations de ces membres et afin
d'être plus sûr dans le choix de certains mots.

ED : Non.  J'ai l'impression que ceux qui travaillent sur un même
article que moi ne maîtrisent pas l'anglais ou n'ont pas l'habitude de
consulter les pages en anglais.

DC : Non.  À part un essai sur [[https://commons.wikimedia.org/wiki/Accueil][Wikimedia Commons]] peu probant.  Et je
me souviens de ma participation au défi « 24h pour un article » : le
but était de traduire à plusieurs des articles jugés de qualité en
anglais, mais c'était un peu trop chacun-dans-son-coin.  Quand il y a
une discussion, c'est sur une traduction déjà publiée, qu'elle soit
achevée ou non.

BE, PM, J : Non.

* Est-ce qu'il vous manque des outils ?  Si oui lesquels ?

CH : Oui. Idéalement, il faudrait quelque chose comme ce site
http://mymemory.translated.net, mais avec un moteur de recherche sur
Wikipédia.

BE : Il manque d'avantage de prise en charge du français sur
Apertium : la qualité est au top, mais il n'y a que deux paires de
langues prises en charge (es->fr, ca->fr).

* Est-ce que vous pensez que l'ajout de contenu par traduction sur Wikipédia renforce la qualité des contenus ?

FF : J'ai traduit [[Giuseppe Pognante]], un italien né en France, depuis
le piémontais et ça donne un contenu qui mentionne pour la première
fois le sentiment anti-italien à la suite de l'assassinat de Sadi
Carnot.  Dans les sources francophones c'est assez rare de le trouver.

CH : Si l'article d'origine est bien développé et sourcé, on bénéficie
de ces sources auxquelles on n'aurait peut-être pas eu accès (ou moins
facilement).

BE : Comme CH.  Et cela permet d'accélérer « [[https://fr.wikipedia.org/wiki/Wikip%25C3%25A9dia:Effet_piranha][l'effet piranha]] » en
ayant une base construite à proposer aux potentiels contributeurs.

ED : Sans doute. Souvent, il me faut aussi entrer dans la page
anglaise pour la compléter.

DC : Oui. Il m'arrive régulièrement que l'article final de la
wikipédia francophone soit plus riche que les originaux, en prenant
des bouts de WPen [la wikipédia anglophone] et WPde [la wikipédia
germanophone], voire d'autres. Et on bénéficie du travail de sourçage
d'autres wikimédiens, je trouve cela précieux.

PM : Oui, dans une certaine mesure.  Mais il y a un défaut : on publie
sans vérifier les sources mentionnées. Je pense que si un contributeur
affirmait faire la même chose à partir de sources en français, on lui
reprocherait son manque de sérieux...  C'est pour ça qu'il faut à mon
avis absolument signaler que c'est une traduction.

CM : Sur le fond, sans doute, tant que l'article d'origine est bon.
Sur la forme, non : dans mon expérience, les articles traduits
comportent souvent des faux sens, des contresens, des anglicismes (ou
autres), voire des phrases incompréhensibles et demandent un gros
travail de révision (qui n'est pas toujours fait), soit que le
traducteur se soit trop reposé sur la traduction automatique, soit
qu'il ne maîtrise pas suffisamment la langue de départ ou d'arrivée,
soit qu'il connaisse mal le domaine... Je prêche pour ma paroisse,
mais la traduction, c'est un métier.

J : Bien sûr, on apporte un point de vue différent sur le contenu. On
évite le "franco-centrage".

* Est-ce qu'il y a des débats internes sur l'utilité des traductions ?

CM : On en a pas mal discuté avec [[https://fr.wikipedia.org/wiki/Utilisateur:DonCamillo][Don Camillo]], mais je n'ai pas
l'impression que cela fasse débat ailleurs dans la communauté. J'ai
l'impression d'être une des rares personnes à ne pas être hyper
favorable à la traduction, pour des raisons pragmatiques (c'est
souvent très mal fait) et idéologiques (à mon sens ça nuit à la
diversité des points de vue, et les sources sont nécessairement en
langues étrangères).

CH : Je suis moi aussi sensible à la diversité des points de vue, mais
dans le domaine de ce que je traduis, je n'ai pas eu à faire face à
des cas litigieux ; de toutes façons, la traduction à partir d'autres
langues « occidentales » n'offre pas une vraie alternative.  Il y a eu
des débats comme celui évoqué par CM, en effet.

ED : Je n'ai pas participé à ces débats.  J'ai l'impression que le
fait de mentionner des sources en langue étrangère dérange. Encore,
des sources anglaises, ça passe mieux.

DC : Dans nos [[https://fr.wikipedia.org/wiki/Wikip%25C3%25A9dia:WikiPermanence][wikipermanences]], mon compère et moi insistons sur
l'existence des articles dans diverses langues et nous encourageons à
y piocher des infos, surtout si elles sont sourcées. Si ces sources
peuvent être remplacées ou complétées par des francophones, c'est du
bonus.

BE : Pareil que CM et DC, bien qu'il y ait peu de débats.  J'apprécie
de pouvoir faire confiance à un contributeur qui participe dans ma
langue, et je fais de même pour un contributeur qui contribue dans une
autre langue.  Il n'y a pas pour moi de contre-indication à traduire.
Et allez trouver une source en français pour un village de Corée ou
une locomotive mexicaine ! Dans les permanences grand public, il y a
une forte demande de personnes souhaitant faire des traductions.

PM : Sur la qualité, oui : les traductions automatiques sont
détestées.  Mais sinon, non.  Et j'ajoute que la version beta de
l'outil de traduction fait discuter les malheureux membres du projet
[[https://fr.wikipedia.org/wiki/Projet:Maintenance][Maintenance]] dont je fais partie : l'outil de traduction a des défauts,
il génère du code inutile, et donc j'espère que l'utilisation de
l'outil ne se répandra pas avant la publication d'une version plus
propre.

