Liste des wikipédiens :

- Florian F. (https://fr.wikipedia.org/wiki/Utilisateur:Otourly)
- Charlotte Matou (https://fr.wikipedia.org/wiki/Utilisateur:Matou91)
- C. Hernandez (https://fr.wikipedia.org/wiki/Utilisateur:Daehan)
- Eduardo (https://fr.wikipedia.org/wiki/Utilisateur:Pradoliv)
- Benoît Evellin (https://fr.wikipedia.org/wiki/Utilisateur:Trizek) - je parle ici en tant que bénévole !
- Dominique (https://fr.wikipedia.org/wiki/Utilisateur:Cbyd)
- Pascal Maillard (https://fr.wikipedia.org/wiki/Utilisateur:Rehtse)
- Mathieu Stumpf Guntz (https://fr.wikipedia.org/wiki/Utilisateur:psychoslave)
- Justine (https://fr.wikipedia.org/wiki/Utilisateur:Pom445)

* Quelle est votre expérience générale de la traduction sur Wikipédia ?

Quelles langues, dans quel(s) but(s), à quelle fréquence, etc. ?

FF : Je traduis un peu depuis les langues romanes, l'italien et le
piémontais, dans le but d'ajouter des articles sur des événements
intéressants non traités sur Wikipédia.

CM : J'ai rarement traduit (ça me rappelle trop le boulot), mais je
révise parfois des traductions, notamment depuis l'anglais, et plus
rarement depuis l'italien et le russe.

CH : La majorité des articles que j'ai créés (plus de 400) sont
traduits depuis les wikipédias anglaise ou espagnole.  J'ai
ponctuellement traduit depuis l'italien et le néerlandais.

ED : Je collabore dans le domaine de la psychanalyse, la littérature,
l'histoire littéraire, le théâtre.  En général, je ne traduis pas
vraiment, je m'inspire plutôt des articles, car les procédures en vue
d'une traduction me semblent assez compliquées.

DC : Je m'intéresse principalement à des biographies de scientifiques
et à des distinctions.  Je remarque que souvent les wikipédias
anglophone et germanophone sont plus complètes.  Quand c'est possible,
j'utilise le wiktionnaire, en le complétant de temps en temps.

BE: Je traduis en fonction des sujets que j'aime bien.  Si l'article
n'existe pas sur la Wikipédia francophone mais qu'il est présent sur
l'anglophone ou l'espagnole, hop, je le traduis.

PM : Je traduis peu.  Je le fais principalement pour tester les outils
de traduction. Je fais beaucoup de maintenance et je trouve important
de comprendre comment on peut commettre des erreurs en utilisant les
outils existant.

MSG: Je traduis des articles de temps en temps depuis l’anglais vers
le français et l’espéranto.  Pour les traductions vers l’espéranto,
les propositions d’apertium FIXME sont souvent justes, et permettent
de gagner du temps, même si ça n’est pas parfait... si ça l'était il
n’y aurait même plus besoin de contribution humaine ^^).  À noter
qu’il existe des traductions entièrement automatisés.

J: Je traduis la plupart du temps depuis l'anglais.  Il m'est arrivé
de travailler à partir du russe, mais cela reste rare.  Mes sujets
sont vastes (histoire, cuisine...).

* Comment choisissez-vous les articles (ou passages) que vous traduisez ?

FF : Découverte fortuite via les articles sans interwikis des
Wikipédia sources ou message en PDD.

CH: Ils entrent dans une thématique sur laquelle je travaille. Je
cherche les liens rouges dans les autres wikipédias.

ED: Quand je travaille sur un article en français, je vérifie ce que
les collègues de langue anglaise en ont fait.

DC : Quand je vois un lien rouge pour lequel je me sens capable
d'apporter qqchose, je vérifie si le sujet existe dans d'autres WP,
via Wikidata notamment. Et un peu aussi des liens qui me font plaisir,
sur des auteurs ou des oeuvres que j'ai appréciés.

PM : depuis en, selon les suggestions du bistro, ou si un lien rouge
me parle dans un article

J:A l'envie, selon les sujet qui m’intéressent, ou que j'estime
incomplets sur wp.

* Comment le(s) traduisez-vous ?

FF : J'utilise des dictionnaires, m'appuyant pour le piémontais sur la
ressemblance avec l'italien et le français, je confronte également les
sources avec si possible des versions francophones.

CH : pour l'anglais et l'espagnol, directement ou en utilisant le dico
en ligne Wordreference pour les mots plus délicats. Je crée l'article
sur wp:fr et traduis directement à la création (pas de brouillon hors
ou dans wp).

ED: Je suis trilingue français - portugais (Brésil) - anglais. A part
cela, je peux lire et comprendre l'espagnol et l'italien. Rarement je
consulte Google traduction pour voir ce qu'ils proposent. je consulte
aussi rarement l'Oxford English Dictionary.

DC : Depuis que j'ai découvert l'outil d'assistance de traduction
(Special:ContentTranslation), je l'utilise plus fréquemment, surtout
depuis l'anglais et un peu l'allemand, rarement d'autres langues. En
cas de lacune de ma part sur un mot ou une tournure, j'utilise wikt ou
des dictionnaires en ligne. Souvent je traduis le RI et une partie du
contenu, j'édite une version inachevée et je complète ma
traduction. Je laisse parfois un paragraphe non traduit, en le
signalant avec le modèle idoine, ou je signale mes doutes en faisant
confiance à l'intelligence collective pour les pallier.

BE: avec l'outil de traduction et, en complément, j'utilise les outils
d'assistance et Linguee pour les expressions idiomatiques

PM : Avec l'outil de traduction.

J:Avec le wiktionnaire, yandex translate et un dictionnaire papier.

* Est-ce qu'il existe des outils de traduction dédiés à l'édition de Wikipédia(s) ?

FF : Je ne sais pas, j'ai déjà utilisé translate wiki pour corriger
l'interface mais je n'utilise pas d'outil pour le contenu.

CH : hormis l'outil de traduction interwiki développé par WM (que je
n'utilise pas), je ne connais pas, non.

ED : Pas que je sache.

BE : Special:ContentTranslation. Cet outil n'a rien à voir avec la
traduction de l'interface : c'est un outil dédié pour traduire des
articles, qui présente une assistance à la traduction (Apertum et
Yandex), la permanence des liens d'un article à l'autre, la
transcription des modèles et plus ! 

DC : Comme BE, un outil certes imparfait mais vraiment pratique pour
certaines parties (catégories, liens, modèles...) et qui s'améliore
d'année en année. 

J: Je ne sais pas.

* Est-ce que la Wikimedia Foundation (ou Wikimédia France) a une politique particulière vis-à-vis des questions de traduction ?

CM : La Fondation s'intéresse de très près à la traduction et cherche
à améliorer les outils. Wikimédia France ne s'est pas vraiment saisi
de la question, bien qu'elle promeuve les wikis en langues de
France. L'asso a été contactée par une plateforme de traduction
(appartenant à une agence) pour que ses membres traduisent des
extraits de l'encyclopédie sur sa plateforme, afin qu'ils puissent
faire démonstration de leurs compétences en traduction.

CH : Le développement de l'outil de traduction interwiki tend à
montrer que c'est un enjeu pour WM, mais je n'en sais pas plus.

ED : Je crois que si, mais cela me semble compliqué, donc je le
contourne.

DC : le déploiement de Wikidata facilite les connexions entre les
wikis et les traductions. Je suppose donc que c'est une volonté
délibérée, sans avoir cherché davantage si c'est une "politique".

PM : il semble.que oui, pour augmenter la quantité d'article, l'impact
sur la quantité étant sans doute un élément facile à évaluer.

* Est-ce que ces outils sont sous licences libres ?

FF : Je n'utilise pas d'outils autre que wiki.

CH : idem.

ED: Je ne sais pas.

BE: Oui ! Apertum a la priorité sur Yandex quand il est disponible.

DC :J'espère bien, question de cohérence !

* Est-ce qu'ils permettent de faire de l'édition collaborative ?

ED : C'est théoriquement possible.

BE: Concernant ContentTranslation, non.  Ou pas encore, mais c'est un
sujet à long terme.

* Comment sait-on si un article de la Wikipédia francophone a été traduit depuis un article d'une Wikipédia d'une autre langue ?

FF : Pour la traduction entre les différents articles on utilise le
modèle {{Traduction/Référence}} qui indique la version d'origine et y
ajoute un lien, il y a aussi le modèle {{Traduit de}} qui est à placer
en PDD (j'utilise que la première solution). Sur Wikinews, où il m'est
également arrivé de traduire des articles, on préfère importer les
articles à traduire, comme ça le bon auteur est réellement crédité et
retrouvable dans l'historique

CH : bien expliqué par FF.

ED : Je ne sais pas. Je l'indique quand la page de Wikipedia me
demande de préciser les modifications que j'ai apportées à l'article.

DC : idem FF. J'avoue ne pas l'avoir fait (par ignorance) durant mes
premières années...

PM : Jusqu'il y a peu, on le savait grâce au modèle
{{Traduction/Référence}}, mais on m'a signalé que ce n'est plus
obligatoire. Comme c'était compliqué pour l'outil de traduction
d'apposer automatiquement le modèle, les légistes de la fondation ont
fini par trouver que finalement un simple lien dans le commentaire de
diff de l'article traduit vers l'article source suffit. Lorsque j'ai
constaté que les nouvelles traductions oubliaient souvent le crédit
d'auteurs, j'ai voulu modifier la page d'aide sur le sujet pour
csigaler que c'est obligatoire, mais j'ai été réverté : ce n'est donc
pas obligatoire. Il faut donc consulter la première ligne de
l'historique d'un article pour le savoir. Auparavant, c'était souvent
omis, et il n'y avait même pas la première ligne de l'historique pour
le savoir.

J: Avec l'ajout du modèle {{Traduction/Référence}}.

* Est-ce que vous vous organisez en ligne avec d'autres pour travailler sur des traductions avant de les poster sur Wikipédia ?

FF : Non, les sujets que je trouve sont trop spécifiques, mais j'en
discute une fois traduit pour que d'autres le complète/corrige s'ils
le souhaitent.

CH : j'ai - rarement : deux fois, de mémoire - créé une simple ébauche
et appelé "à l'aide" sur un projet lié ou un utilisateur en
particulier, pour profiter des spécialisations de ces membres et afin
d'être plus sûr dans le choix de certains mots. L'ébauche ne contenant
pas encore la traduction, j'espère que ce commentaire reste pertinent
vis-à-vis de la question ^^

ED: Non. J'ai l'impression que ceux qui travaillent sur un même
article que moi ne mapitrisent pas l'anglais ou n'ont pas l'habitude
de consulter les pages en anglais.

Dc : non. à part un essai sur Commons pas vraiment probant ; et je me
souviens de ma participation à "24h pour un article" où le but était
de traduire à plusieurs des articles jugés de qualité en anglais, mais
un peu trop chacun-dans-son-coin. Quand il y a eu discussion, c'est
sur une traduction déjà publiée, qu'elle soit achevée ou non
(concours, par ex).

BE : absolument pas.

PM : Non

J:Non

* Si oui, quels outils utilisez-vous pour ce travail offline ?

* Est-ce qu'il vous manque des outils ?  Si oui lesquels ?

FF : pas pour mon usage.

CH : Oui. Idéalement, il faudrait quelque chose comme ce site
http://mymemory.translated.net/ , mais avec un moteur de recherche sur
Wikipédia.

ED : Je ne saurai pas dire. Quelque chose de plsu perfectionné que
Google Traduction, peut-être. 

BE: Il maque d'avantage de prise en charge du français sur Apertium :
la qualité est au top, mais il n'y a que deux paires de langues prises
en charge (es->fr, ca->fr).

PM : idem BE, et surtout une version plus au point que la version beta

* Est-ce que vous pensez que l'ajout de contenu par traduction sur Wikipédia renforce la qualité des contenus ?

FF : J'ai traduit [[Giuseppe Pognante]], un italien né en France, depuis
le piémontais et on obtient un contenu qui mentionne pour la première
fois le sentiment anti-italien résultant de l'assassinat de Sadi
Carnot. Dans les sources francophones c'est assez rare de le trouver.

CH : Si l'article d'origine est bien développé et sourcé, on bénéficie
de ces sources auxquelles on n'aurait peut-être pas eu accès (ou moins
facilement).

ED: Sans doute. Souvent, il me faut aussi entrer dans la page anglaise
pour la compléter.

DC : Oui. Il m'arrive régulièrement que l'article WPfr final soit plus
riche que les originaux, en prenant des bouts de WPen et WPde, voire
d'autres. Et on bénéficie du travail de sourçage d'autres wikimédiens,
je trouve cela précieux.

BE: comme CH. Et cela permet d'accélérer l'effet piranha en ayant une
base construite à proposer aux potentiels contributeurs.

PM : Oui, dans une certaine mesure. Mais il y a un défaut : on publie
sans vérifier les sources mentionnées. Je pense que si un contributeur
affirmait faire la même chose à partir de sources en français, on lui
reprocherait son manque de sérieux...  C'est pour ça qu'à mon qu'il
faut absolument signaler que c'est une traduction.

CM : Sur le fond, sans doute, tant que l'article d'origine est
bon. Sur la forme, non : dans mon expérience (je ne me prononce
évidemment pas sur les personnes ici, je ne pense pas avoir eu
l'occasion de relire leur travail), les articles traduits comportent
souvent des faux sens, des contresens, des anglicismes (ou autres),
voire des phrases incompréhensibles et demandent un gros travail de
révision (qui n'est pas toujours fait), soit que le traducteur se soit
trop reposé sur la traduction automatique, soit qu'il ne maîtrise pas
suffisamment la langue de départ ou d'arrivée, soit qu'il connaisse
mal le domaine... Je prêche pour ma paroisse, mais la traduction,
c'est un métier.

J:Bien sur, on apporte un point de vue différent sur le contenu. On
évite le "franco-centrage".

* Est-ce qu'il y a des débats internes (à Wikimédia ou dans les communautés wikipédias) sur l'utilité des traductions ?

CM : On en a pas mal discuté avec Don Camillo, mais je n'ai pas
l'impression que ça fasse débat ailleurs dans la communauté. J'ai
l'impression d'être une des rares personnes à ne pas être hyper
favorable à la traduction, pour des raisons pragmatiques (c'est
souvent très mal fait) et idéologiques (à mon sens ça nuit à la
diversité des points de vue, et les sources sont nécessairement en
langues étrangères).

FF : Je n'ai pas participé à des débats sur le sujet.

CH : Je suis moi aussi sensible à la diversité des points de vue, mais
dans le domaine de ce que je traduis, je n'ai pas fait face à ces cas
litigieux, et de toutes façons, la traduction à partir d'autres
langues "occidentales" n'offre pas une vraie alternative. Il y a eu
des débats comme celui évoqué par CM, en effet.

ED : Je n'ai pas participé à ces débats. J'ai l'impression que le fait
de mentionner des sources en langue étrangère dérange. Encore, des
sources anglaises, ça passe mieux.

DC : dans nos wikipermanences, mon compère et moi insistons sur
l'existence des articles dans diverses langues et de ne pas hésiter à
y piocher des infos, surtout si elles sont sourcées. Si ces sources
peuvent être remplacées ou complétées par des francophones, c'est du
bonus.

BE: idem CM et DC, bien qu'il y ai peu de débats. J'apprécie de
pouvoir faire confiance à un contributeur qui participe dans ma
langue, et je fais de même pour un contributeur qui contribue dans une
autre langue. Il n'y a pas pour moi de contre-indication à traduire
(et va trouver une source en français pour un village de Corée ou une
locomotive mexicaine...). Dans les permanences grand public, il y a
une forte demande de personnes souhaitant faire des traductions.

PM : Non. Sur la qualtié, oui : les traductions automatiques sont
détestées. Et j'ajoute que la version beta fait discuter les
malheureux membres du projet maintenance dont je fais partie : l'ouitl
de traduction a des défauts, il génère du code inutile, et donc
j'espère que l'utilisation de l'outil ne se répandra pas avant la
publication d'une version plus propre.

J: Pas que je sache.
