#+title: Plongée dans la traduction collaborative chez Framasoft

* Comment fonctionnent les traductions d'articles sur le Framablog ?

# De la sélection des articles à traduire à la publication et à la modération des commentaires.

Tout est fait de manière communautaire.  Un·e membre du groupe
[[http://framablog.org/2008/12/04/framalang-la-traduction-sur-framasoft/][Framalang]] propose aux autres une traduction sur notre liste de
discussion.  Dès que deux ou trois membres annoncent qu'ils sont
d'accord pour traduire ensemble, nous préparons le texte et lançons la
la traduction sur un pad.

Il y a en général deux phases.  La première est une phase de
traduction « brute », où le plus de gens possible interviennent pour
traduire collaborativement le texte : chacun·e son paragraphe, même si
chacun peut intervenir sur les traductions des autres ou échanger en
direct sur les choix de traduction de tel ou tel terme.  La deuxième
phase est une phase de relecture, où quelques volontaires relisent le
texte pour trancher dans les choix de traduction restants, vont aussi
homogénéiser la traduction, chasser les coquilles, les anglicismes et
les faux-amis.

Enfin, quelques membres du groupe parmi ceux qui ont un compte sur le
Framablog reprennent le pad pour le mettre en page sur le blog, en y
ajoutant un chapô pour contextualiser l'article, les sources, des
illustrations, les mentions des traducteurs et traductrices.

Une fois l'article publié, c'est l'équipe du Framablog qui se charge
de répondre aux commentaires et de les modérer, mais nous avons de la
chance : nous avons un lectorat très respectueux.

* Quels outils (libres!) utilisez-vous ? 

Nous hébergeons nos listes de discussion avec [[https://www.sympa.org][Sympa]], nous utilisons
[[https://framapad.org][Framapad]] (notre instance d'Etherpad) avec l’extension [[https://mypads.framapad.org/mypads/][MyPads]] pour la
traduction collaborative, et [[https://wordpress.org/][Wordpress]] pour ce qui est du blog.

Le groupe a aussi développé un petit outil de suivi en PHP qui nous
permet de retrouver facilement les adresses des pads et de suivre leur
avancement.

Enfin, pour nous détendre, nous avons ouvert une équipe « Le bar
Framalang » sur [[https://framateam.org/][Framateam]], une instance de [[http://www.mattermost.org][Mattermost]].  Mais c'est
juste un espace de convivialité pour éviter d'inonder les listes
d'e-mails : il est interdit d'y parler boulot dessus ^^ !

* Est-ce qu'il y a des outils qui vous manquent ?  Si oui, lesquels ?

Il nous manque surtout... du temps !

Certes il manque souvent des mémoires de traduction, mais comme chaque
projet de traduction est unique (un article de presse, un tutoriel de
logiciel, etc.) il nous suffit souvent de tenir à jour une liste de
termes sur la traduction desquels nous sommes d'accord pour harmoniser
l'ensemble de la traduction à la fin.

Pour des projets plus conséquents, nous utilisons le même outil que
chez Mozilla francophone, le [[https://transvision.mozfr.org][Transvision]] : cette interface permet de
trouver des traductions déjà effectuées dans de nombreux logiciels et
de nombreuses pages web, et ceci dans plus d'une centaine de langues.

* Quels conseils donneriez-vous à des groupes qui veulent traduire à plusieurs ?

Il faut veiller à conjuguer horizontalité et verticalité.

C'est-à-dire qu'il faut dans un premier temps ouvrir l'accès à la
traduction au plus grand nombre : la phase de premier jet s'enrichit
des suggestions multiples et des regards croisés.

Pour cette première phase horizontale, il faut deux choses : un outil
collaboratif immédiatement accessible, et une bonne dose de tolérance
et de modestie.

Concernant l'outil, c'est l'exigence d'horizontalité qui explique
notre choix du pad.  Il faut avoir bien présent à l'esprit que les
compétences d'un bon traducteur sont d'abord linguistiques et non
informatiques.  Si l'on souhaite recruter des traducteurs du meilleur
niveau possible, il ne faut pas les décourager en leur proposant des
outils demandant une initiation trop longue et des compétences
techniques.  [[https://git-scm.com/][Git]], par exemple, est un excellent outil de développement
collaboratif pour le code, mais son accès peut tenir à l'écart de
nombreuses personnes qui apporteraient des éléments de traduction
précieux et qui ne franchiront pas l'obstacle d'un apprentissage de
plus.  De même, un outil ergonomique comme Transifex, très en vogue,
rend des services précieux, mais comme toutes les plateformes de
traduction qui découpent les textes en chaînes à traduire, il rend
difficile l'accès au contexte, qui est un élément décisif pour
déterminer une traduction optimale.

Pour ce qui est de la tolérance, elle va avec l'outil : lorsqu'on
travaille à plusieurs sur un pad, chacun peut voir d'un instant à
l'autre sa traduction contestée, modifiée ou annulée (pas de panique,
la sauvegarde des modifications est automatique.)  Chacun doit donc
accepter l'idée que personne ne détient la meilleure traduction,
malgré les certitudes, le niveau d'études, le bilinguisme, les
références convoquées, etc.  D'autre part, les traducteur·ice·s
médiocres, ça existe : il faut considérer qu'en se confrontant aux
autres, ils et elles apprendront à s'améliorer et il ne faut pas les
exclure.  C'est difficile à admettre, mais un « mauvais » traducteur
qui prend en charge un paragraphe de dix lignes, suivi d'un correcteur
qui révise efficacement, produisent à deux un travail plus rapide et
plus efficace qu'un « bon » traducteur qui va chercher longtemps et
seul la formulation idéale, laquelle exigera de toutes façons une
révision.

Vient ensuite le moment plus « vertical » où l'on passe à un groupe
plus restreint disposant de compétences plus pointues et qui va
pratiquer les révisions nécessaires jusqu'à la phase finale.  Cette
verticalité n'est pas un élitisme : elle repose plutôt sur la
spécialisation.  Ce groupe est ouvert à toute personne qui dispose des
compétences nécessaires : il comprend par exemple des « typonazis » et
des « grammarnazis ».  Ces appellations sont à prendre au second
degré : il s'agit de personnes très exigeantes qui vont effectuer des
corrections, des mises en forme, nettoyer les inévitables coquilles,
ajouter les espaces insécables, traquer le solécisme, défoncer le
barbarisme, débusquer les impropriétés... bref : s'efforcer de donner
au rendu final une qualité la plus proche possible de la qualité
professionnelle.

Une dernière chose : toujours privilégier les contributeur·ice·s qui
maîtrisent le mieux la langue cible, plutôt que ceux qui maîtrisent
surtout la langue source.  Avec l'expérience, il nous semble
indispensable que le rendu final soit contrôlé par un francophone
natif lorsqu'on traduit vers le français, par un anglophone natif
lorsqu'on traduit vers l'anglais, etc.  Les cas de vrai bilinguisme
sont assez rares.  Il faut que le lecteur oublie qu'il s'agit d'une
traduction !

