#+title: Interview d'Alexandre Franke, coordinateur de l'équipe de traduction du projet GNOME

Cette interview est sous licence [[https://creativecommons.org/licenses/by-sa/][CC by-sa 4.0]].

* Bonjour Alexandre.  Peux-tu nous présenter le projet GNOME en quelques mots ?

GNOME est avant tout un environnement de bureau pour les plate-formes Unix. Son approche est d'offrir quelque chose de simple d'accès, encourageant la productivité et agréable à utiliser.

C'est également un ensemble de technologies qui sont développées pour cet environnement mais sont utilisées même en-dehors.

Enfin, c'est une communauté de personnes qui se soucient de fournir au plus grand nombre un accès à la technologie dans le respect des valeurs du logiciel libre, avec une attention particulière sur des sujets comme la sécurité, le respect de la vie privée, l'éducation, ou l'accès pour les personnes en situation de handicap.

* Tu es coordinateur de la traduction de GNOME vers le français.  En quoi consiste la traduction pour GNOME, et en quoi consiste ton travail de coordination ?

GNOME se découpe en plusieurs « lots » à traduire :

 * le cœur, constitué de briques logiciels sans lesquelles l'environnement ne fonctionnerait pas (comme gnome-control-center qui apparait à l'utilisateur francophone sous le nom « Paramètres »)
 * les applications qui apportent des fonctionnalités, comme Météo, Horloges, Polari (client IRC)…
 * la documentation (manuels de l'environnement et des applications, mais aussi des guides pour les développeurs et administrateurs)

Il y a en outre quelques projets qui sortent de ces cadres, par exemple les [[https://www.youtube.com/watch?v=LhY7rpWXm1Y][vidéos qui accompagnent chaque nouvelle version]] tous les six mois ont des sous-titres traduits.

Le coordinateur se charge de communiquer à l'équipe les priorités du moment, d'indiquer aux relecteurs les travaux en attente quand ça dure un peu trop, de motiver l'équipe, d'arbitrer en cas de désaccord et à la fin il met la main à la pâte pour pousser les derniers bouts afin d'être dans les temps. Il veille aussi à la cohérence des termes employés à travers l'ensemble des logiciels et à ce que les retours des utilisateurs soient bien pris en compte.

Par ailleurs, je suis membre de l'équipe de coordination de l'internationalisation. Ce sont en quelque sorte les coordinateurs des coordinateurs, mais ils jouent aussi un rôle de conseil auprès des développeurs quand ceux-ci ne sont pas sûrs de la meilleure manière de gérer une situation concernant la traduction de leurs logiciels.

* Est-ce que GNOME travaille de façon différente de KDE ?

À ma connaissance, personne ou presque ne travaille comme GNOME dans le monde du logiciel libre. Nous utilisons comme KDE et la plus grande partie des logiciels libres le format po et comme eux nous les complétons avec des éditeurs hors ligne. En revanche nous avons un [[https://l10n.gnome.org/help/vertimus_workflow/1][flux de travail]] et [[https://l10n.gnome.org/][un outil]] (libre) qui n'ont jusqu'à présent pas été adoptés par d'autres.

Je fais régulièrement des conférences à des évènements libristes à travers le monde pour partager nos bonnes pratiques et il y a des échanges avec d'autres communautés.

* Est-ce que vous avez des échanges réguliers avec les développeurs de GNOME ?  Est-ce que les traducteurs débordent parfois de leur cadre et interviennent parfois sur le texte original, sa présentation, voire même l'ergonomie ?

Les traducteurs sont parmi les premiers utilisateurs des nouvelles versions des logiciels, parce qu'ils doivent les tester avant que celles-ci ne soient publiées. En conséquence, ils sont les premiers à voir les problèmes que peuvent poser certaines chaînes de caractères et à les remonter aux développeurs. Ils sont aussi bien souvent sensibilisés aux différences entre les langues et capables de reconnaitre les tournures qui ne fonctionneront pas dans certaines traductions, ce qui les amène effectivement à faire changer la présentation ou l'ergonomie. Enfin, en traduisant on peut être amené à réveler des ambiguïtés qui sont alors corrigées ou expliquées dans la version originale.

* Qu'est-ce qui t'a amené à faire cela ?  Qu'est-ce qui te pousse à continuer ?

J'étais étudiant en informatique en 2004 et j'ai découvert dans ce cadre le système d'exploitation Linux et le logiciel libre. Après l'avoir utilisé et appris comment il était écrit, j'ai voulu participer mais je ne pensais pas encore avoir le niveau pour toucher au code et comme j'étais bon en anglais, la traduction était une évidence pour moi. J'ai commencé par Ubuntu et comme une grande partie de ce que j'utilisais sous Ubuntu venait de GNOME, je suis remonté en amont pour que mes traductions profitent à tous les utilisateurs de cet environnement, qu'ils soient sur Ubuntu ou une autre distribution.

Depuis, j'ai acquis d'autres responsabilités au sein du projet et mon implication fait de la communauté GNOME une famille pour moi.

* Est-ce que vous êtes tous volontaires, ou bien avez-vous recours à des professionnels ?

La traduction de GNOME est entièrement bénévole. La plupart des traducteurs font autre chose dans la vie, mais certains d'entre nous sont des professionnels du domaine. C'est mon cas, la traduction technique étant un des services que je propose à mes clients.

* Est-ce que c’est une expérience que tu arrives à valoriser ailleurs que dans « le libre » ?

Absolument. D'une part j'ai quelques clients qui viennent à moi par ce biais, d'autre part j'y ai consacré tellement de temps que je ne distingue pas ça d'autres expérience professionnelles quand je suis amené à dérouler mon CV. Le niveau de qualité des traductions de GNOME, résultat de notre flux de travail, aide beaucoup dans cette valorisation.

* Un dernier mot pour encourager des futurs contributeurs ?

Ne vous laissez pas décourager par les critiques faites sur votre travail. Les contributeurs expérimentés ont tendance à ne pas enrober leurs propos et à dire de manière assez directe ce qu'il faut améliorer pour que le travail puisse être intégré. Dites vous que s'ils prennent le temps de faire leurs remarques, c'est qu'ils voient dans vos contributions un potentiel et que votre travail a donc de la valeur. Persévérez, il n'y a rien de plus gratifiant que de voir le fruit de ses efforts être accepté après l'avoir peaufiné.
